name: tictactoe
description: Tic Tac Toe for iOS & Android
publish_to: 'none'

version: 1.2.0+8

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  envied: ^0.3.0
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.4.0
  in_app_purchase: ^3.1.5
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
